In [1]:
import pandas as pd

path = "/Users/naruebet.orgl/Workspace/Labs/rnd_ai/internal_raw/formula_ingredients_data.csv"

In [2]:
pd.set_option('display.max_columns', None)
df = pd.read_csv(path)

/var/folders/_9/265g29r95n730k3qwnws2l380000gn/T/ipykernel_13379/2739277719.py:2: DtypeWarning: Columns (8,30,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [3]:
df.head()

,id,rd_formula_id,rm_lines_id,rmit_code,rmit_name,rmit_trade_name,rmit_inci_name,master_formula,supplier_code,supplier_name_th,supplier_name_en,rm_price,rm_price_unit,rm_bulk_price,rm_bulk_price_bg,rm_bulk_unit,line_number,mix_number_line,rm_part,toa,users_id,created_at,updated_at,rm_cost,rm_cost_kg,value_to_mf,total_weight,value_kg,value_g,pu_note,rd_formula_line_note,rd_formula_line_sts_id,rd_formula_line_sts_detail
0,1,RDF2208001,NaN,Water,NaN,Water,Water,85.4,NaN,NaN,NaN,1.0,0.0,0.854,0.04,NaN,1,NaN,A,NaN,NaN,NaN,2025-09-01 15:42:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,RDF2208001,NaN,RC00Y001,NaN,Glycerin,Glycerin,1.0,SP001,NaN,Triple nine,65.0,0.0,0.650,3.25,NaN,2,NaN,A,NaN,NaN,NaN,2025-09-01 15:42:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,RDF2208001,NaN,RC00R008,NaN,Radianol 4710,Propylene glycol,3.0,SP001,NaN,Triple nine,200.0,0.0,6.000,10.00,NaN,3,NaN,B,NaN,NaN,NaN,2025-09-01 15:42:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,RDF2208001,NaN,RC00R001,NaN,HEC,Hydroxyethyl cellulose,2.0,SP002,NaN,DKSH,330.0,0.0,6.600,16.50,NaN,4,NaN,B,NaN,NaN,NaN,2025-09-01 15:42:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,RDF2208001,NaN,RC00H003,NaN,Oligo Hya,NaN,0.2,SP003,NaN,Bonanzaneutra,17000.0,0.0,34.000,850.00,NaN,5,NaN,B,NaN,NaN,NaN,2025-09-01 15:42:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN